export default {
  products: [
    { id:13,
      img: "assets/images/room/bedroom/1.jpg",
      view_img_product: [
        "assets/images/room/bedroom/img_view_prd/1-1.jpg",
        "assets/images/room/bedroom/img_view_prd/1-2.jpg",
        "assets/images/room/bedroom/img_view_prd/1-3.jpg",
      ],
      name: "Ghế bành Viking Freja",
      price: 1100000,
      quantity: 1,
      colors: ["Xanh", "Đỏ"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng ngủ",
      materials: ["Gỗ - Bọc Vải"],
    },
    { id:23,
      img: "assets/images/room/bedroom/2.jpg",
      view_img_product: [
        "assets/images/room/bedroom/img_view_prd/2-1.jpg",
        "assets/images/room/bedroom/img_view_prd/2-2.jpg",
      ],
      name: "Ghế bành NanJing",
      price: 1492500,
      quantity: 1,
      colors: ["Nâu đen"],
      sizes: ["Lớn", "Vừa"],
      category: "Phòng ngủ",
      materials: ["Gỗ - Bọc Da"],
    },
    { id:33,
      img: "assets/images/room/bedroom/3.jpg",
      view_img_product: [
        "assets/images/room/bedroom/img_view_prd/3-1.jpg",
        "assets/images/room/bedroom/img_view_prd/3-2.jpg",
        "assets/images/room/bedroom/img_view_prd/3-3.jpg",
      ],
      name: "Sofa giường Temasek",
      price: 1990000,
      quantity: 1,
      colors: ["Đỏ"],
      sizes: ["Vừa", "Nhỏ"],
      category: "Phòng ngủ",
      materials: ["Gỗ - Bọc Vải"],
    },
    { id:43,
      img: "assets/images/room/bedroom/4.jpg",
      view_img_product: [
        "assets/images/room/bedroom/img_view_prd/4-1.jpg",
        "assets/images/room/bedroom/img_view_prd/4-2.jpg",
      ],
      name: "Bàn góc Caruso",
      price: 1290000,
      quantity: 1,
      colors: ["Vàng"],
      sizes: ["Lớn", "Vừa"],
      category: "Phòng ngủ",
      materials: ["Gỗ"],
    },
    { id:53,
      img: "assets/images/room/bedroom/5.jpg",
      view_img_product: [
        "assets/images/room/bedroom/img_view_prd/5-1.jpg",
        "assets/images/room/bedroom/img_view_prd/5-2.jpg",
        "assets/images/room/bedroom/img_view_prd/5-3.jpg",
      ],
      name: "Giường ngủ bọc vải Pio 1m8 hiện đại",
      price: 7690000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Lớn", "Vừa"],
      category: "Phòng ngủ",
      materials: ["Gỗ - Bọc Vải"],
    },
    { id:63,
      img: "assets/images/room/bedroom/6.jpg",
      view_img_product: [
        "assets/images/room/bedroom/img_view_prd/6-1.jpg",
        "assets/images/room/bedroom/img_view_prd/6-2.jpg",
        "assets/images/room/bedroom/img_view_prd/6-3.jpg",
      ],
      name: "Bàn đầu giường City sơn trắng",
      price: 2630000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng ngủ",
      materials: ["Gỗ"],
    },
    { id:73,
      img: "assets/images/room/bedroom/7.jpg",
      view_img_product: [
        "assets/images/room/bedroom/img_view_prd/7-1.jpg",
        "assets/images/room/bedroom/img_view_prd/7-2.jpg",
        "assets/images/room/bedroom/img_view_prd/7-3.jpg",
      ],
      name: "Giường ngủ gỗ Victoria 1m8",
      price: 4270000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Lớn", "Vừa"],
      category: "Phòng ngủ",
      materials: ["Gỗ - Bọc Vải"],
    },
    { id:83,
      img: "assets/images/room/bedroom/8.jpg",
      view_img_product: [
        "assets/images/room/bedroom/img_view_prd/8-1.jpg",
        "assets/images/room/bedroom/img_view_prd/8-2.jpg",
        "assets/images/room/bedroom/img_view_prd/8-3.jpg",
      ],
      name: "Tủ áo Victoria",
      price: 2370000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Vừa", "Nhỏ"],
      category: "Phòng ngủ",
      materials: ["Gỗ"],
    },
    { id:93,
      img: "assets/images/room/bedroom/9.jpg",
      view_img_product: [
        "assets/images/room/bedroom/img_view_prd/9-1.jpg",
        "assets/images/room/bedroom/img_view_prd/9-2.jpg",
      ],
      name: "Giường hộc kéo Iris 1m6 Stone",
      price: 6250000,
      quantity: 1,
      colors: ["Xám"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng ngủ",
      materials: ["Gỗ - Bọc Vải"],
    },
    { id:103,
      img: "assets/images/room/bedroom/10.jpg",
      view_img_product: [
        "assets/images/room/bedroom/img_view_prd/10-1.jpg",
        "assets/images/room/bedroom/img_view_prd/10-2.jpg",
        "assets/images/room/bedroom/img_view_prd/10-3.jpg",
      ],
      name: "Giường ngủ bọc da Mây 1m8 Fango",
      price: 4230000,
      quantity: 1,
      colors: ["Vàng"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng ngủ",
      materials: ["Gỗ - Bọc Da"],
    },
    { id:113,
      img: "assets/images/room/bedroom/11.jpg",
      view_img_product: [
        "assets/images/room/bedroom/img_view_prd/11-1.jpg",
        "assets/images/room/bedroom/img_view_prd/11-2.jpg",
      ],
      name: "Đôn Mây - da Fango",
      price: 1260000,
      quantity: 1,
      colors: ["Nâu"],
      sizes: ["Lớn", "Vừa"],
      category: "Phòng ngủ",
      materials: ["Gỗ - Bọc Da"],
    },
    { id:123,
      img: "assets/images/room/bedroom/12.jpg",
      view_img_product: [
        "assets/images/room/bedroom/img_view_prd/12-1.jpg",
        "assets/images/room/bedroom/img_view_prd/12-2.jpg",
        "assets/images/room/bedroom/img_view_prd/12-3.jpg",
      ],
      name: "Giường ngủ gỗ Maxine 1m8",
      price: 6260000,
      quantity: 1,
      colors: ["Nâu"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng ngủ",
      materials: ["Gỗ"],
    },
  ],
};
