export default {
  products: [
    { id:16,
      img: "assets/images/room/room_decorations/1.jpg",
      view_img_product: [
        "assets/images/room/room_decorations/img_view_prd/1-1.jpg",
        "assets/images/room/room_decorations/img_view_prd/1-2.jpg",
        "assets/images/room/room_decorations/img_view_prd/1-3.jpg",
      ],
      name: "Đệm ngồi Viking Kudde",
      price: 1190000,
      quantity: 1,
      colors: ["Đỏ", "Ghi"],
      sizes: ["Vừa", "Nhỏ"],
      category: "Đồ trang trí",
      materials: ["Gỗ - Bọc Vải"],
    },
    { id:26,
      img: "assets/images/room/room_decorations/2.jpg",
      view_img_product: [
        "assets/images/room/room_decorations/img_view_prd/2-1.jpg",
      ],
      name: "Móc dán tường Elektra",
      price: 13000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Lớn", "Vừa"],
      category: "Đồ trang trí",
      materials: ["Khác"],
    },

    { id:36,
      img: "assets/images/room/room_decorations/3.jpg",
      view_img_product: [
        "assets/images/room/room_decorations/img_view_prd/3-1.jpg",
        "assets/images/room/room_decorations/img_view_prd/3-2.jpg",
      ],
      name: "Miếng bọc cạnh bàn Elektra",
      price: 11000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Đồ trang trí",
      materials: ["Khác"],
    },
    { id:46,
      img: "assets/images/room/room_decorations/4.jpg",
      view_img_product: [
        "assets/images/room/room_decorations/img_view_prd/4-1.jpg",
        "assets/images/room/room_decorations/img_view_prd/4-2.jpg",
      ],
      name: "Thiết bị chốt an toàn Elektra",
      price: 39000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Lớn", "Vừa", "Nhỏ"],
      category: "Đồ trang trí",
      materials: ["Khác"],
    },
    { id:56,
      img: "assets/images/room/room_decorations/5.jpg",
      view_img_product: [
        "assets/images/room/room_decorations/img_view_prd/5-1.jpg",
        "assets/images/room/room_decorations/img_view_prd/5-2.jpg",
      ],
      name: "Vải bọc ghế đôn",
      price: 199000,
      quantity: 1,
      colors: ["Hoa văn"],
      sizes: ["Lớn", "Vừa", "Nhỏ"],
      category: "Đồ trang trí",
      materials: ["Khác"],
    },
    { id:66,
      img: "assets/images/room/room_decorations/6.jpg",
      view_img_product: [
        "assets/images/room/room_decorations/img_view_prd/6-1.jpg",
      ],
      name: "Bộ 2 chuông chim gốm trắng",
      price: 899000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Lớn", "Vừa", "Nhỏ"],
      category: "Đồ trang trí",
      materials: ["Khác"],
    },
    { id:76,
      img: "assets/images/room/room_decorations/7.jpg",
      view_img_product: [
        "assets/images/room/room_decorations/img_view_prd/7-1.jpg",
      ],
      name: "Bộ 2 chân nến Black Iris 111209",
      price: 1357000,
      quantity: 1,
      colors: ["Vàng"],
      sizes: ["Lớn", "Vừa", "Nhỏ"],
      category: "Đồ trang trí",
      materials: ["Khác"],
    },
    { id:86,
      img: "assets/images/room/room_decorations/8.jpg",
      view_img_product: [
        "assets/images/room/room_decorations/img_view_prd/8-1.jpg",
        "assets/images/room/room_decorations/img_view_prd/8-2.jpg",
        "assets/images/room/room_decorations/img_view_prd/8-3.jpg",
      ],
      name: "Cây để giấy cuộn nhà bếp Black Orchid",
      price: 4900000,
      quantity: 1,
      colors: ["Đen"],
      sizes: ["Lớn", "Vừa", "Nhỏ"],
      category: "Đồ trang trí",
      materials: ["Khác"],
    },
    { id:96,
      img: "assets/images/room/room_decorations/9.jpg",
      view_img_product: [
        "assets/images/room/room_decorations/img_view_prd/9-1.jpg",
        "assets/images/room/room_decorations/img_view_prd/9-2.jpg",
        "assets/images/room/room_decorations/img_view_prd/9-3.jpg",
      ],
      name: "Cây để giấy cuộn nhà bếp Black Orchid",
      price: 6700000,
      quantity: 1,
      colors: ["Đen"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Đồ trang trí",
      materials: ["Khác"],
    },
    { id:106,
      img: "assets/images/room/room_decorations/10.jpg",
      view_img_product: [
        "assets/images/room/room_decorations/img_view_prd/10-1.jpg",
        "assets/images/room/room_decorations/img_view_prd/10-2.jpg",
      ],
      name: "chân nến Butterfly Ginkgo mẫu 2",
      price: 7600000,
      quantity: 1,
      colors: ["Đen"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Đồ trang trí",
      materials: ["Khác"],
    },
    { id:116,
      img: "assets/images/room/room_decorations/11.jpg",
      view_img_product: [
        "assets/images/room/room_decorations/img_view_prd/11-1.jpg",
        "assets/images/room/room_decorations/img_view_prd/11-2.jpg",
        "assets/images/room/room_decorations/img_view_prd/11-3.jpg",
      ],
      name: "Gía để rượu Black Orchid",
      price: 4520000,
      quantity: 1,
      colors: ["Đen"],
      sizes: ["Lớn", "Vừa"],
      category: "Đồ trang trí",
      materials: ["Khác"],
    },
    { id:126,
      img: "assets/images/room/room_decorations/12.jpg",
      view_img_product: [
        "assets/images/room/room_decorations/img_view_prd/12-1.jpg",
        "assets/images/room/room_decorations/img_view_prd/12-2.jpg",
      ],
      name: "Tượng trang trí hình cầu thang",
      price: 3600000,
      quantity: 1,
      colors: ["Vàng"],
      sizes: ["Vừa", "Nhỏ"],
      category: "Đồ trang trí",
      materials: ["Khác"],
    },
  ],
};
