export default {
  products: [
    { id:12,
      img: "assets/images/room/dining_room/1.jpg",
      view_img_product: [
        "assets/images/room/dining_room/img_view_prd/1-1.jpg",
        "assets/images/room/dining_room/img_view_prd/1-2.jpg",
        "assets/images/room/dining_room/img_view_prd/1-3.jpg",
      ],
      name: "Bộ bàn ăn Stefano",
      price: 14950000,
      quantity: 1,
      colors: ["Xám", "Vàng"],
      sizes: ["Lớn", "Vừa"],
      category: "Phòng ăn",
      materials: ["Gỗ - Bọc Vải"],
    },
    { id:22,
      img: "assets/images/room/dining_room/2.jpg",
      view_img_product: [
        "assets/images/room/dining_room/img_view_prd/2-1.jpg",
        "assets/images/room/dining_room/img_view_prd/2-2.jpg",
      ],
      name: "Bộ bàn ăn Marryland",
      price: 3990000,
      quantity: 1,
      colors: ["Vàng"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng ăn",
      materials: ["Gỗ"],
    },
    { id:32,
      img: "assets/images/room/dining_room/3.jpg",
      view_img_product: [
        "assets/images/room/dining_room/img_view_prd/3-1.jpg",
        "assets/images/room/dining_room/img_view_prd/3-2.jpg",
      ],
      name: "Bộ bàn ăn Edward",
      price: 1290000,
      quantity: 1,
      colors: ["Vàng", "Nâu đen"],
      sizes: ["Vừa", "Nhỏ"],
      category: "Phòng ăn",
      materials: ["Gỗ"],
    },
    { id:42,
      img: "assets/images/room/dining_room/4.jpg",
      view_img_product: [
        "assets/images/room/dining_room/img_view_prd/4-1.jpg",
        "assets/images/room/dining_room/img_view_prd/4-2.jpg",
      ],
      name: "Bàn ăn 1m8 Elegance màu tự nhiên",
      price: 3540000,
      quantity: 1,
      colors: ["Vàng"],
      sizes: ["Vừa", "Lớn"],
      category: "Phòng ăn",
      materials: ["Gỗ"],
    },
    { id:52,
      img: "assets/images/room/dining_room/5.jpg",
      view_img_product: [
        "assets/images/room/dining_room/img_view_prd/5-1.jpg",
        "assets/images/room/dining_room/img_view_prd/5-2.jpg",
        "assets/images/room/dining_room/img_view_prd/5-3.jpg",
      ],
      name: "Ghế ăn có tay Elegance màu tự nhiên",
      price: 1240000,
      quantity: 1,
      colors: ["Vàng"],
      sizes: ["Vừa", "Lớn"],
      category: "Phòng ăn",
      materials: ["Gỗ"],
    },
    { id:62,
      img: "assets/images/room/dining_room/6.jpg",
      view_img_product: [
        "assets/images/room/dining_room/img_view_prd/6-1.jpg",
        "assets/images/room/dining_room/img_view_prd/6-2.jpg",
        "assets/images/room/dining_room/img_view_prd/6-3.jpg",
      ],
      name: "Bàn ăn Mây 8 chỗ",
      price: 2440000,
      quantity: 1,
      colors: ["Nâu"],
      sizes: ["Vừa"],
      category: "Phòng ăn",
      materials: ["Gỗ"],
    },
    { id:72,
      img: "assets/images/room/dining_room/7.jpg",
      view_img_product: [
        "assets/images/room/dining_room/img_view_prd/7-1.jpg",
        "assets/images/room/dining_room/img_view_prd/7-2.jpg",
      ],
      name: "Ghế ăn Mây - da Mushroom",
      price: 1040000,
      quantity: 1,
      colors: ["Vàng"],
      sizes: ["Vừa"],
      category: "Phòng ăn",
      materials: ["Gỗ - Bọc Da"],
    },
    { id:82,
      img: "assets/images/room/dining_room/8.jpg",
      view_img_product: [
        "assets/images/room/dining_room/img_view_prd/8-1.jpg",
        "assets/images/room/dining_room/img_view_prd/8-2.jpg",
      ],
      name: "Bộ bàn ăn Victoria 6 chỗ vải Iris B1702-03",
      price: 13740000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Lớn", "Vừa"],
      category: "Phòng ăn",
      materials: ["Gỗ - Bọc Vải"],
    },
    { id:92,
      img: "assets/images/room/dining_room/9.jpg",
      view_img_product: [
        "assets/images/room/dining_room/img_view_prd/9-1.jpg",
        "assets/images/room/dining_room/img_view_prd/9-2.jpg",
      ],
      name: "Bench Victoria - Vải Iris B1702",
      price: 1730000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Lớn", "Vừa"],
      category: "Phòng ăn",
      materials: ["Gỗ - Bọc Vải"],
    },
    { id:102,
      img: "assets/images/room/dining_room/10.jpg",
      view_img_product: [
        "assets/images/room/dining_room/img_view_prd/10-1.jpg",
        "assets/images/room/dining_room/img_view_prd/10-2.jpg",
        "assets/images/room/dining_room/img_view_prd/10-3.jpg",
      ],
      name: "Bàn ăn gỗ Pio 6 chỗ 1m8",
      price: 3640000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng ăn",
      materials: ["Gỗ"],
    },
    { id:112,
      img: "assets/images/room/dining_room/11.jpg",
      view_img_product: [
        "assets/images/room/dining_room/img_view_prd/11-1.jpg",
        "assets/images/room/dining_room/img_view_prd/11-2.jpg",
        "assets/images/room/dining_room/img_view_prd/11-3.jpg",
      ],
      name: "Ghế Pio - vải LDN",
      price: 1540000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng ăn",
      materials: ["Gỗ - Bọc Vải"],
    },
    { id:122,
      img: "assets/images/room/dining_room/12.jpg",
      view_img_product: [
        "assets/images/room/dining_room/img_view_prd/12-1.jpg",
        "assets/images/room/dining_room/img_view_prd/12-2.jpg",
        "assets/images/room/dining_room/img_view_prd/12-3.jpg",
      ],
      name: "Bàn Console Bolero",
      price: 1720000,
      quantity: 1,
      colors: ["Xám"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng ăn",
      materials: ["Gỗ"],
    },
  ],
};
