export default {
  products: [
    { id:15,
      img: "assets/images/room/kitchen/1.jpg",
      view_img_product: [
        "assets/images/room/kitchen/img_view_prd/1-1.jpg",
        "assets/images/room/kitchen/img_view_prd/1-2.jpg",
      ],
      name: "Khăn tay Soft",
      price: 39000,
      quantity: 1,
      colors: ["Xanh", "Nâu"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng bếp",
      materials: ["Khác"],
    },
    { id:25,
      img: "assets/images/room/kitchen/2.jpg",
      view_img_product: [
        "assets/images/room/kitchen/img_view_prd/2-1.jpg",
        "assets/images/room/kitchen/img_view_prd/2-2.jpg",
      ],
      name: "Túi đựng đồ giặt Lynn",
      price: 49000,
      quantity: 1,
      colors: ["Trắng", "Đỏ"],
      sizes: ["Lớn", "Vừa"],
      category: "Phòng bếp",
      materials: ["Khác"],
    },
    { id:35,
      img: "assets/images/room/kitchen/3.jpg",
      view_img_product: [
        "assets/images/room/kitchen/img_view_prd/3-1.jpg",
        "assets/images/room/kitchen/img_view_prd/3-2.jpg",
      ],
      name: "Đôn mềm Connemara",
      price: 4490000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Vừa", "Nhỏ"],
      category: "Phòng bếp",
      materials: ["Gỗ - Bọc Vải"],
    },
    { id:45,
      img: "assets/images/room/kitchen/4.jpg",
      view_img_product: [
        "assets/images/room/kitchen/img_view_prd/4-1.jpg",
        "assets/images/room/kitchen/img_view_prd/4-2.jpg",
      ],
      name: "Đĩa hoa nở màu vàng",
      price: 2500000,
      quantity: 1,
      colors: ["Vàng"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng bếp",
      materials: ["Khác"],
    },
    { id:55,
      img: "assets/images/room/kitchen/5.jpg",
      view_img_product: ["assets/images/room/kitchen/img_view_prd/5-1.jpg"],
      name: "Gía để khăn ăn White Orchid",
      price: 3300000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Vừa", "Nhỏ"],
      category: "Phòng bếp",
      materials: ["Khác"],
    },
    { id:65,
      img: "assets/images/room/kitchen/6.jpg",
      view_img_product: [
        "assets/images/room/kitchen/img_view_prd/6-1.jpg",
        "assets/images/room/kitchen/img_view_prd/6-2.jpg",
        "assets/images/room/kitchen/img_view_prd/6-3.jpg",
      ],
      name: "Hũ và muỗng Pomegranate mini",
      price: 3800000,
      quantity: 1,
      colors: ["Vàng"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng bếp",
      materials: ["Khác"],
    },
    { id:75,
      img: "assets/images/room/kitchen/7.jpg",
      view_img_product: [
        "assets/images/room/kitchen/img_view_prd/7-1.jpg",
        "assets/images/room/kitchen/img_view_prd/7-2.jpg",
      ],
      name: "Khay bánh Calla lily",
      price: 8800000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Lớn"],
      category: "Phòng bếp",
      materials: ["Khác"],
    },
    { id:85,
      img: "assets/images/room/kitchen/8.jpg",
      view_img_product: [
        "assets/images/room/kitchen/img_view_prd/8-1.jpg",
        "assets/images/room/kitchen/img_view_prd/8-2.jpg",
        "assets/images/room/kitchen/img_view_prd/8-2.jpg",
      ],
      name: "Khay bánh Butterfly Ginkgo",
      price: 8100000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Vừa"],
      category: "Phòng bếp",
      materials: ["Khác"],
    },
    { id:95,
      img: "assets/images/room/kitchen/9.jpg",
      view_img_product: [
        "assets/images/room/kitchen/img_view_prd/9-1.jpg",
        "assets/images/room/kitchen/img_view_prd/9-2.jpg",
      ],
      name: "Ly sứ Filter Imany",
      price: 580000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Vừa"],
      category: "Phòng bếp",
      materials: ["Khác"],
    },
    { id:105,
      img: "assets/images/room/kitchen/10.jpg",
      view_img_product: [
        "assets/images/room/kitchen/img_view_prd/10-1.jpg",
        "assets/images/room/kitchen/img_view_prd/10-2.jpg",
        "assets/images/room/kitchen/img_view_prd/10-3.jpg",
      ],
      name: "Tô trang trí Butterfly Ginkgo",
      price: 2480000,
      quantity: 1,
      colors: ["Vàng"],
      sizes: ["Lớn"],
      category: "Phòng bếp",
      materials: ["Khác"],
    },
    { id:115,
      img: "assets/images/room/kitchen/11.jpg",
      view_img_product: [
        "assets/images/room/kitchen/img_view_prd/11-1.jpg",
        "assets/images/room/kitchen/img_view_prd/11-2.jpg",
        "assets/images/room/kitchen/img_view_prd/11-3.jpg",
      ],
      name: "Xô đá Wisteria gold",
      price: 9880000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Lớn"],
      category: "Phòng bếp",
      materials: ["Khác"],
    },
    { id:125,
      img: "assets/images/room/kitchen/12.jpg",
      view_img_product: [
        "assets/images/room/kitchen/img_view_prd/12-1.jpg",
        "assets/images/room/kitchen/img_view_prd/12-2.jpg",
        "assets/images/room/kitchen/img_view_prd/12-3.jpg",
      ],
      name: "Đĩa hình chim công",
      price: 360000,
      quantity: 1,
      colors: ["Trắng", "Xanh", "Hồng"],
      sizes: ["Vừa"],
      category: "Phòng bếp",
      materials: ["Khác"],
    },
  ],
};
