export default {
  products: [
    { id:11,
      img: "assets/images/room/living_room/1.jpg",
      view_img_product: [
        "assets/images/room/living_room/img_view_prd/1-1.jpg",
        "assets/images/room/living_room/img_view_prd/1-2.jpg",
        "assets/images/room/living_room/img_view_prd/1-3.jpg",
      ],
      name: "Tủ TV FreeStyle",
      price: 6990000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Vừa", "Nhỏ"],
      category: "Phòng khách",
      materials: ["Gỗ"],
    },
    { id:21,
      img: "assets/images/room/living_room/2.jpg",
      view_img_product: [
        "assets/images/room/living_room/img_view_prd/2-1.jpg",
        "assets/images/room/living_room/img_view_prd/2-2.jpg",
        "assets/images/room/living_room/img_view_prd/2-3.jpg",
      ],
      name: "Ghế bành Domingo",
      price: 3290000,
      quantity: 1,
      colors: ["Nâu"],
      sizes: ["Lớn", "Vừa"],
      category: "Phòng khách",
      materials: ["Gỗ - Bọc Da"],
    },

    { id:31,
      img: "assets/images/room/living_room/3.jpg",
      view_img_product: [
        "assets/images/room/living_room/img_view_prd/3-1.jpg",
        "assets/images/room/living_room/img_view_prd/3-2.jpg",
        "assets/images/room/living_room/img_view_prd/3-3.jpg",
      ],
      name: "Kệ TV Mozart",
      price: 2990000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Vừa", "Nhỏ"],
      category: "Phòng khách",
      materials: ["Gỗ"],
    },
    { id:41,
      img: "assets/images/room/living_room/4.jpg",
      view_img_product: [
        "assets/images/room/living_room/img_view_prd/4-1.jpg",
        "assets/images/room/living_room/img_view_prd/4-2.jpg",
        "assets/images/room/living_room/img_view_prd/4-3.jpg",
      ],
      name: "Kệ TV Batista",
      price: 5990000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng khách",
      materials: ["Gỗ"],
    },
    { id:51,
      img: "assets/images/room/living_room/5.jpg",
      view_img_product: [
        "assets/images/room/living_room/img_view_prd/5-1.jpg",
        "assets/images/room/living_room/img_view_prd/5-2.jpg",
      ],
      name: "Ghế đôn Carnaby",
      price: 2490000,
      quantity: 1,
      colors: ["Ghi", "Xám"],
      sizes: ["Lớn", "Vừa"],
      category: "Phòng khách",
      materials: ["Gỗ - Bọc Vải"],
    },
    { id:61,
      img: "assets/images/room/living_room/7.jpg",
      view_img_product: [
        "assets/images/room/living_room/img_view_prd/7-1.jpg",
        "assets/images/room/living_room/img_view_prd/7-2.jpg",
      ],
      name: "Ghế đẩu Sacramento",
      price: 1990000,
      quantity: 1,
      colors: ["Nâu", "Nâu đen"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng khách",
      materials: ["Gỗ - Bọc Da"],
    },
    { id:71,
      img: "assets/images/room/living_room/9.jpg",
      view_img_product: ["assets/images/room/living_room/img_view_prd/9-1.jpg"],
      name: "Bàn cafe Cabaret",
      price: 1390000,
      quantity: 1,
      colors: ["Đen"],
      sizes: ["Vừa", "Nhỏ"],
      category: "Phòng khách",
      materials: ["Gỗ"],
    },
    { id:81,
      img: "assets/images/room/living_room/10.jpg",
      view_img_product: [
        "assets/images/room/living_room/img_view_prd/10-1.jpg",
        "assets/images/room/living_room/img_view_prd/10-2.jpg",
        "assets/images/room/living_room/img_view_prd/10-3.jpg",
      ],
      name: "Ghế bành Bogart",
      price: 5490000,
      quantity: 1,
      colors: ["Hồng tím", "Xanh", "Ghi"],
      sizes: ["Lớn", "Vừa"],
      category: "Phòng khách",
      materials: ["Gỗ - Bọc Vải"],
    },
    { id:91,
      img: "assets/images/room/living_room/11.jpg",
      view_img_product: [
        "assets/images/room/living_room/img_view_prd/11-1.jpg",
        "assets/images/room/living_room/img_view_prd/11-2.jpg",
        "assets/images/room/living_room/img_view_prd/11-3.jpg",
      ],
      name: "Ghế bành Connemara",
      price: 7490000,
      quantity: 1,
      colors: ["Xám", "Xanh"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng khách",
      materials: ["Gỗ - Bọc Vải"],
    },
    { id:101,
      img: "assets/images/room/living_room/12.jpg",
      view_img_product: [
        "assets/images/room/living_room/img_view_prd/12-1.jpg",
        "assets/images/room/living_room/img_view_prd/12-2.jpg",
        "assets/images/room/living_room/img_view_prd/12-3.jpg",
      ],
      name: "Ghế đôn chicago",
      price: 999000,
      quantity: 1,
      colors: ["Trắng", "Đỏ", "Ghi"],
      sizes: ["Lớn", "Vừa"],
      category: "Phòng khách",
      materials: ["Gỗ - Bọc Vải"],
    },
    { id:111,
      img: "assets/images/room/living_room/13.jpg",
      view_img_product: [
        "assets/images/room/living_room/img_view_prd/13-1.jpg",
        "assets/images/room/living_room/img_view_prd/13-2.jpg",
        "assets/images/room/living_room/img_view_prd/13-3.jpg",
      ],
      name: "Ghế bành trẻ em - Viking Junior",
      price: 699000,
      quantity: 1,
      colors: ["Đỏ"],
      sizes: ["Vừa", "Nhỏ"],
      category: "Phòng khách",
      materials: ["Gỗ - Bọc Vải"],
    },
    { id:121,
      img: "assets/images/room/living_room/14.jpg",
      view_img_product: [
        "assets/images/room/living_room/img_view_prd/14-1.jpg",
        "assets/images/room/living_room/img_view_prd/14-2.jpg",
      ],
      name: "Sofa Idasy 3C (có Đôn)",
      price: 7800000,
      quantity: 1,
      colors: ["Vàng", "Xám"],
      sizes: ["Lớn"],
      category: "Phòng khách",
      materials: ["Gỗ - Bọc Vải"],
    },
  ],
};
