export default {
  products: [
    { id:14,
      img: "assets/images/room/work_room/1.jpg",
      view_img_product: [
        "assets/images/room/work_room/img_view_prd/1-1.jpg",
        "assets/images/room/work_room/img_view_prd/1-2.jpg",
      ],
      name: "Sofa giường",
      price: 2990000,
      quantity: 1,
      colors: ["Xám"],
      sizes: ["Lớn", "Vừa"],
      category: "Phòng làm việc",
      materials: ["Gỗ - Bọc Vải"],
    },
    { id:24,
      img: "assets/images/room/work_room/2.jpg",
      view_img_product: [
        "assets/images/room/work_room/img_view_prd/2-1.jpg",
        "assets/images/room/work_room/img_view_prd/2-2.jpg",
      ],
      name: "Kệ sách FreeStyle",
      price: 6490000,
      quantity: 1,
      colors: ["Trắng", "Vàng"],
      sizes: ["Vừa", "Nhỏ"],
      category: "Phòng làm việc",
      materials: ["Gỗ"],
    },
    { id:34,
      img: "assets/images/room/work_room/3.jpg",
      view_img_product: [
        "assets/images/room/work_room/img_view_prd/3-1.jpg",
        "assets/images/room/work_room/img_view_prd/3-2.jpg",
        "assets/images/room/work_room/img_view_prd/3-3.jpg",
      ],
      name: "Kệ TV Cobra",
      price: 6490000,
      quantity: 1,
      colors: ["Vàng"],
      sizes: ["Lớn", "Vừa"],
      category: "Phòng làm việc",
      materials: ["Gỗ"],
    },
    { id:44,
      img: "assets/images/room/work_room/4.jpg",
      view_img_product: [
        "assets/images/room/work_room/img_view_prd/4-1.jpg",
        "assets/images/room/work_room/img_view_prd/4-2.jpg",
        "assets/images/room/work_room/img_view_prd/4-3.jpg",
      ],
      name: "Bàn làm việc Osaka KA",
      price: 5490000,
      quantity: 1,
      colors: ["Nâu", "Nâu đen"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng làm việc",
      materials: ["Gỗ"],
    },
    { id:54,
      img: "assets/images/room/work_room/5.jpg",
      view_img_product: [
        "assets/images/room/work_room/img_view_prd/5-1.jpg",
        "assets/images/room/work_room/img_view_prd/5-2.jpg",
        "assets/images/room/work_room/img_view_prd/5-3.jpg",
      ],
      name: "Bàn làm việc Skagen",
      price: 2590000,
      quantity: 1,
      colors: ["Nâu"],
      sizes: ["Lớn", "Vừa"],
      category: "Phòng làm việc",
      materials: ["Gỗ"],
    },
    { id:64,
      img: "assets/images/room/living_room/6.jpg",
      view_img_product: [
        "assets/images/room/living_room/img_view_prd/6-1.jpg",
        "assets/images/room/living_room/img_view_prd/6-2.jpg",
      ],
      name: "Ghế thư giãn Sitting Bull",
      price: 1790000,
      quantity: 1,
      colors: ["Nâu đen"],
      sizes: ["Lớn", "Vừa"],
      category: "Phòng làm việc",
      materials: ["Gỗ"],
    },
    { id:74,
      img: "assets/images/room/work_room/7.jpg",
      view_img_product: [
        "assets/images/room/work_room/img_view_prd/7-1.jpg",
        "assets/images/room/work_room/img_view_prd/7-2.jpg",
      ],
      name: "Kệ sách Maxine - 4 tầng/2 ngăn kéo",
      price: 2330000,
      quantity: 1,
      colors: ["Nâu"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng làm việc",
      materials: ["Gỗ"],
    },
    { id:84,
      img: "assets/images/room/work_room/8.jpg",
      view_img_product: [
        "assets/images/room/work_room/img_view_prd/8-1.jpg",
        "assets/images/room/work_room/img_view_prd/8-2.jpg",
      ],
      name: "Kệ Sách Artigo",
      price: 3510000,
      quantity: 1,
      colors: ["Nâu đen"],
      sizes: ["Vừa", "Nhỏ"],
      category: "Phòng làm việc",
      materials: ["Gỗ"],
    },
    { id:94,
      img: "assets/images/room/work_room/9.jpg",
      view_img_product: [
        "assets/images/room/work_room/img_view_prd/9-1.jpg",
        "assets/images/room/work_room/img_view_prd/9-2.jpg",
        "assets/images/room/work_room/img_view_prd/9-3.jpg",
      ],
      name: "Bàn làm việc Kate",
      price: 2420000,
      quantity: 1,
      colors: ["Trắng"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng làm việc",
      materials: ["Gỗ"],
    },
    { id:104,
      img: "assets/images/room/work_room/10.jpg",
      view_img_product: [
        "assets/images/room/work_room/img_view_prd/10-1.jpg",
        "assets/images/room/work_room/img_view_prd/10-2.jpg",
        "assets/images/room/work_room/img_view_prd/10-3.jpg",
      ],
      name: "Kệ treo tường Natura",
      price: 1320000,
      quantity: 1,
      colors: ["Ghi"],
      sizes: ["Vừa", "Nhỏ"],
      category: "Phòng làm việc",
      materials: ["Gỗ"],
    },
    { id:114,
      img: "assets/images/room/work_room/11.jpg",
      view_img_product: [
        "assets/images/room/work_room/img_view_prd/11-1.jpg",
        "assets/images/room/work_room/img_view_prd/11-2.jpg",
        "assets/images/room/work_room/img_view_prd/11-3.jpg",
      ],
      name: "Bàn làm việc Maxine",
      price: 5260000,
      quantity: 1,
      colors: ["Nâu đen"],
      sizes: ["Lớn", "Nhỏ"],
      category: "Phòng làm việc",
      materials: ["Gỗ"],
    },
    { id:124,
      img: "assets/images/room/work_room/12.jpg",
      view_img_product: [
        "assets/images/room/work_room/img_view_prd/12-1.jpg",
        "assets/images/room/work_room/img_view_prd/12-2.jpg",
        "assets/images/room/work_room/img_view_prd/12-3.jpg",
      ],
      name: "Bàn làm việc Barbier",
      price: 3460000,
      quantity: 1,
      colors: ["Vàng"],
      sizes: ["Vừa", "Nhỏ"],
      category: "Phòng làm việc",
      materials: ["Gỗ"],
    },
  ],
};
